# Generated by Django 4.2 on 2023-06-12 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dermatologist',
            old_name='houry_rate',
            new_name='hourly_rate',
        ),
    ]
