# Generated by Django 4.2 on 2023-06-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_houry_rate_dermatologist_hourly_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='day_of_week',
            field=models.CharField(max_length=10),
        ),
    ]
