# Generated by Django 4.2 on 2023-05-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_appointmentchat_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='dermatologist_rejected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_rejected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='dermatologist_approved',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_approved',
            field=models.DateTimeField(null=True),
        ),
    ]
