# Generated by Django 4.2 on 2023-05-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_appointment_dermatologist_rejected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='date',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
