# Generated by Django 4.2 on 2023-05-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_chatmessage_date_alter_chatmessage_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='extra_info',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appo_date',
            field=models.DateTimeField(null=True),
        ),
    ]
