# Generated by Django 4.2 on 2023-06-16 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_slot_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='action',
            field=models.CharField(choices=[('Treatment', 'Treatment'), ('Referral', 'Referral'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='dermatologist',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dermatologist'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prediction',
            name='treatment',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('route', models.CharField(max_length=255)),
                ('related_id', models.IntegerField(null=True)),
                ('related_name', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
