# Generated by Django 4.2 on 2023-05-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appointment_extra_info_alter_appointment_appo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
