# Generated by Django 4.2 on 2023-06-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_diagnosis_action_diagnosis_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='extra_derm_info',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
