# Generated by Django 4.2 on 2023-05-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_appointment_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dermatologist',
            old_name='work_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='dermatologist',
            old_name='phone_number_1',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='dermatologist',
            name='phone_number_2',
        ),
    ]
