# Generated by Django 4.2 on 2023-06-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_notification_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='dermatologist_approved',
            new_name='dermatologist_cancelled',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='dermatologist_rejected',
            new_name='dermatologist_removed',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_approved',
            new_name='patient_cancelled',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_rejected',
            new_name='patient_removed',
        ),
        migrations.AddField(
            model_name='dermatologist',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='PENDING', max_length=100),
        ),
    ]
