from api.models.dermatologist import Dermatologist
from api.models.diagnosis import Diagnosis
from api.models.disease import Disease
from api.models.patient import Patient
from api.models.chat_message import ChatMessage
from api.models.treatment import Treatment
from api.models.appointment import Appointment
from api.models.appointment_chat import AppointmentChat
from api.models.prediction import Prediction